# File: .streamlit/secrets.toml
# Ini adalah cara paling aman untuk menyimpan key di Streamlit saat develop lokal.

GEMINI_API_KEY="AIzaSyAqs6hnP6jAOjiaPn-rk3l2d5vbN1zuk1s" 
# <-- Masukkan API Key lo di sini (tanpa spasi!)